######################################################################
# Automatically generated by qmake (3.0) ? 6? 4 18:25:36 2014
######################################################################

TEMPLATE = app
TARGET = drawSVG
QT += core gui svg
QMAKE_CXXFLAGS += -std=c++11
CONFIG += c++11
INCLUDEPATH += . ../..

macx {
    QMAKE_CXXFLAGS += -stdlib=libc++ -mmacosx-version-min=10.7
    INCLUDEPATH += /usr/local/include
}

# Input
SOURCES += main.cpp
